### ISSUE TITLE
language creator is a bird-girl

### ISSUE THREAD

**Issue by kyurivlis** [alphaziguana/story-of-eberban#1]

**Comment by alphaziguana** [comment]
As I mentioned, I didn't know a lot about the lang at the time I wrote the story and I know nothing about its creator personally. The story is meant to be satirical and not to reflect reality in any way. Changing "man-boy" to "bird-girl" would hurt the story imho.

Maybe this is satirical too. I'm not great at distinguishing that. Idk feel free to elaborate
